export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AGENCY_REPOSITORY = Symbol('AGENCY_REPOSITORY');
export const AGENCY_MEMBER_REPOSITORY = Symbol('AGENCY_MEMBER_REPOSITORY');
export const TRIP_REPOSITORY = Symbol('TRIP_REPOSITORY');
export const EXPEDITION_REPOSITORY = Symbol('EXPEDITION_REPOSITORY');
