-- Seed de ciudades de Colombia
-- Insertar ciudades principales de Colombia (evitando duplicados)

INSERT INTO cities (name_city)
SELECT DISTINCT unnest
FROM (SELECT unnest(ARRAY[
  'Bogotá',
  'Medellín',
  'Cali',
  'Barranquilla',
  'Cartagena',
  'Bucaramanga',
  'Pereira',
  'Santa Marta',
  'Manizales',
  'Cúcuta',
  'Villavicencio',
  'Pasto',
  'Valledupar',
  'Montería',
  'Armenia',
  'Sincelejo',
  'Popayán',
  'Tunja',
  'Ibagué',
  'Riohacha',
  'Florencia',
  'Quibdó',
  'Neiva',
  'Yopal',
  'Mocoa',
  'Mitú',
  'Leticia',
  'Inírida',
  'San Andrés',
  'Arauca',
  'Turbo',
  'Apartadó',
  'Palmira',
  'Bello',
  'Soledad',
  'Envigado',
  'Soacha',
  'Itagüí',
  'Buenaventura',
  'Tuluá',
  'Dosquebradas',
  'Floridablanca',
  'Piedecuesta',
  'Girón',
  'La Estrella',
  'Copacabana',
  'Caucasia',
  'Magangué',
  'Maicao',
  'Barrancabermeja',
  'Tumaco',
  'Ipiales',
  'Ocaña',
  'El Carmen de Viboral',
  'Facatativá',
  'Chía',
  'Zipaquirá',
  'Mosquera',
  'Madrid',
  'Funza',
  'Girardot',
  'Fusagasugá',
  'Sogamoso',
  'Duitama',
  'Jamundí',
  'Yumbo'
]))
) AS cities_data(unnest)
WHERE NOT EXISTS (
  SELECT 1 FROM cities WHERE LOWER(name_city) = LOWER(cities_data.unnest)
);
